<?php

/**
 * @file
 * Sends and logs Drupal mails in CiviCRM.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function maillog_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.civicrmmailer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('CiviCRM Mailer sends all emails through CiviCRM.') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('The mailer from CiviCRM (ex: if you are using a third-party, you only need one set of credentials).') . '</dt>';
      $output .= '<dt>' . t('Track outgoing emails on the contact record (see who has requested a password reset, filled in a webform, etc).') . '</dt>';
      $output .= '</dl>';
      return $output;
  }
}
